## YOUR SOLUTION HERE ##
plt.plot(line_data.month_name, line_data.alice_springs_avg_high, color='green', linestyle='dotted', label='Alice Springs')
plt.plot(line_data.month_name, line_data.windhoek_avg_high, color='green', linestyle='dashed', label='Windhoek')
plt.plot(line_data.month_name, line_data.quito_avg_high, color='steelblue', linewidth=2.5, label='Quito')
plt.plot(line_data.month_name, line_data.samarqand_avg_high, color='darkorange', linestyle='dotted', label='Samarqand')
plt.plot(line_data.month_name, line_data.london_avg_high, color='darkorange', linestyle='dashed', label='London')
plt.plot(line_data.month_name, line_data.kodiak_avg_high, color='darkorange', linestyle='solid', label='Kodiak')
plt.title('Average High Temps Around the World, 2020')
plt.ylabel('Temperature (F)')
plt.xlabel('Month')
plt.tick_params(axis='x', labelrotation=45)
plt.legend(bbox_to_anchor = (1, .75))
plt.show()

plt.savefig('line_chart.png')
