## YOUR SOLUTION HERE ##
fig = plt.figure(figsize=(18,16), facecolor='lightgray', tight_layout=True) 
fig.suptitle('Species Counts in Primary, Secondary, and Selectively Logged Tapajos Forests', fontsize=20, y=1)
plt.subplot(3,1,1)
plt.bar(PF_data.genus, PF_data.counts)
plt.xlabel('Primary Forest', fontsize=14)
plt.ylim((0,105))
plt.xlim((-3,105))
plt.xticks(rotation=-90, fontsize=13)
plt.subplot(3,1,2)
plt.bar(SF_data.genus, SF_data.counts)
plt.xlabel('Secondary Forest', fontsize=14)
plt.ylim((0,105))
plt.xlim((-3,105))
plt.xticks(rotation=-90, fontsize=13)
plt.subplot(3,1,3)
plt.bar(SLF_data.genus, SLF_data.counts)
plt.xlabel('Selectively Logged Forest', fontsize=14)
plt.ylim((0,105))
plt.xlim((-3,105))
plt.xticks(rotation=-90, fontsize=13)
plt.show()
