## YOUR SOLUTION HERE ##
plt.suptitle('Relationship between Popularity and ______')
plt.subplot(3,4,1)
plt.scatter(scatter_data.popularity, scatter_data.acousticness, alpha=0.05)
plt.title('acousticness')
plt.subplot(3,4,2)
plt.scatter(scatter_data.popularity, scatter_data.danceability, alpha=0.05)
plt.title('danceability')
plt.subplot(3,4,3)
plt.scatter(scatter_data.popularity, scatter_data.duration_ms, alpha=0.05)
plt.title('duration_ms')
plt.subplot(3,4,4)
plt.scatter(scatter_data.popularity, scatter_data.energy, alpha=0.05)
plt.title('energy')
plt.subplot(3,4,5)
plt.scatter(scatter_data.popularity, scatter_data.instrumentalness, alpha=0.05)
plt.title('instrumentalness')
plt.subplot(3,4,6)
plt.scatter(scatter_data.popularity, scatter_data.liveness, alpha=0.05)
plt.title('liveness')
plt.subplot(3,4,7)
plt.scatter(scatter_data.popularity, scatter_data.loudness, alpha=0.05)
plt.title('loudness')
plt.subplot(3,4,8)
plt.scatter(scatter_data.popularity, scatter_data.speechiness, alpha=0.05)
plt.title('speechiness')
plt.subplot(3,4,9)
plt.scatter(scatter_data.popularity, scatter_data.tempo, alpha=0.05)
plt.title('tempo')
plt.subplot(3,4,10)
plt.scatter(scatter_data.popularity, scatter_data.valence, alpha=0.05)
plt.title('valence')
plt.subplot(3,4,11)
plt.scatter(scatter_data.popularity, scatter_data.key, alpha=0.05)
plt.title('key')
plt.subplot(3,4,12)
plt.scatter(scatter_data.popularity, scatter_data.popularity, alpha=0.05)
plt.title('popularity')
plt.subplots_adjust(hspace=0.5, wspace=0.3)
plt.show()
